### ISSUE TITLE
Description in English

### ISSUE THREAD

**Issue by vds2212** [xqin/gvimext.dll#1]
Sir,

Thanks you very much for this contribution. It works very well for me.
Being not a Chinese reader I found the home page a bit confusing.
If you are interested I would be glad to provide an English translation for the home page.

Thanks again for your contribution,
Best regards,
Vivian.

**Comment by xqin** [comment]
yes, it's ok.
thank you very much.

**Comment by vds2212** [comment]
Here is a first try:

This module improves the Windows Explorer integration of gVim.

It add two context menu items to the Windows Explorer:
- Edit with Vim
- Diff with Vim (when more than one file is selected but less than five)

It add the vimicon to the context menu.
If the file is already open in gVim the extension will switch to that tab.
If the shift key is hold then a new instance of gVim will be started to edit the file.

To install the extension:
- copy the correct (x64 or Win32) gvimext.dll in the folder of the restart_explorer.bat
- Adapt the restart_explorer.bat script to your vim installation path and
- Run the script.

The code have been tested under Windows 7.
It has been compiled with VisualStudio 2010.

The screencast.png is a screenshot of the Windows Explorer with the new gVimExt.
